[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2C7BE5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FC"
textColor = "#000000"
font = "sans serif"
